### ISSUE TITLE
Navigating back to the home page

### ISSUE THREAD

**Issue by wfdd** [everypolitician/everypolitician-docs#16]
Clicking on the logo should probably take you to http://everypolitician.org/; I don't see any way to navigate to the main site other than editing the URL manually.

**Comment by davewhiteland** [comment]
Ah, I think this is an issue specifically with the documentation pages: the logo _is_ wired to the home page, but when we broke the docs out onto a separate subdomain, we didn't spot this.  So once you're on a page being served from http://docs.everypolitician.org, the logo is linking... to the wrong home page. (i.e., the docs subdomain, not the core http://everypolitician.org one).

Good spot @wfdd, thanks!
