### ISSUE TITLE
mention spreadsheets as sources in "how we import data"

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician-docs#34]
The page at https://github.com/everypolitician/everypolitician-docs/blob/gh-pages/submitting.html explains the CSV properties our importer wants, but neglects to point out that this can be simply achieved with, say, a Google Spreadsheet with these columns.

It's implicit if you're already into this world (because the CSV can be inferred from "spreadsheet"), but ought to be explicitly stated: as we already do in several places, the bot is happy to pull data directly from a Google spreadsheet (as CSV) without needing an intermediate scraper... provided the column names are correct.

**Comment by tmtmtmtm** [comment]
superseded by #43
